"""create base models

Revision ID: 5816b7a90d18
Revises: 2c9bb38b85bd
Create Date: 2025-11-07 11:06:17.107059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5816b7a90d18'
down_revision = '2c9bb38b85bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_amount', sa.Integer(), nullable=True),
    sa.Column('invested_amount', sa.Integer(), nullable=True),
    sa.Column('fully_invested', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_id'), 'donation', ['id'], unique=False)
    op.add_column('charityproject', sa.Column('full_amount', sa.Integer(), nullable=True))
    op.add_column('charityproject', sa.Column('invested_amount', sa.Integer(), nullable=True))
    op.add_column('charityproject', sa.Column('fully_invested', sa.Boolean(), nullable=True))
    op.add_column('charityproject', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('charityproject', sa.Column('close_date', sa.DateTime(), nullable=True))
    op.add_column('charityproject', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'description')
    op.drop_column('charityproject', 'close_date')
    op.drop_column('charityproject', 'create_date')
    op.drop_column('charityproject', 'fully_invested')
    op.drop_column('charityproject', 'invested_amount')
    op.drop_column('charityproject', 'full_amount')
    op.drop_index(op.f('ix_donation_id'), table_name='donation')
    op.drop_table('donation')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
